### ISSUE TITLE
Container async tests break when not loaded via flag -- container.html

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#107]
@krisk I'll show you what I mean on Friday if this does not make sense. 

Works:
node build.js --test -- container.html

Does not work:
node build.js --test

**Comment by krisk** [comment]
Nice.  I'll take a look.

**Comment by krisk** [comment]
Problem is that the async load test container are inside the unit-test folder.  The test framework expects every file in that folder to be a QUnit testable file, that is, it expect them to contain a "run()" function.  The easy fix is to put them somewhere else.  The good fix is to make the tester smarter.  So, I shall implement the good fix.

**Comment by Iheartweb** [comment]
Sounds good

**Comment by krisk** [comment]
There's another problem.

Async tests in QUnit should be handled like this:

``` javascript
asyncTest('some random test', function() {
  // I'm using a timer in this example to resemble some async operation
  setTimeout(function() { 
      ok(true, 'always true'); 
      start();  // tells the QUnit test to start
  }, 200);
});
```

Which is somewhat equivalent to doing something like this:

``` javascript
test('some random test', function() {
  stop() // Tell QUnit not to run this test just yet
  setTimeout(function() { 
      ok(true, 'always true'); 
      start();  // tells the QUnit test to start
  }, 200);
});
```

Note that QUnit async tests are ran consecutively.  That is, if there are 2 async tests specified - test1 and test2, test2 will run after test1 has finished.  

### What about tests that contain multiple async operations?

If you're using the `test` function (and not the `asynctest`), for every async operation, include a `start` as a well as a corresponding `stop`.  For example:

``` javascript
test('some random test', function() {
  stop()
  stop();

  setTimeout(function() { 
      ok(true, 'always true'); 
      start();
  }, 200);

  setTimeout(function() { 
      ok(true, 'always true'); 
      start();
  }, 200)
});
```

##### Using Deferreds

Frankly, I'm not a fan of implementing async tests using `test` and the `stop()` operation.  A better way would be to using `asyncTest` with jQuery Deferreds, in the following way:

``` javascript
asyncTest('some async test', function() {

  var deferredA = $.Deferred(),
      deferredB = $.Deferred();

  // Async operation A
  setTimeout(function() {
      ok(true, 'always true');
      deferredA.resolve();
  }, 200);

  // Async operation B
  setTimeout(function() {
      ok(true, 'always true');
      deferredB.resolve();
  }, 200);

  // When both deferreds have been resolved, tell Qunit to start.
  $.when(deferredA, deferredB).done(function() {
    start();
  });

});
```

### Timers?

I'm not entirely sure if timers are reliable enough for testing the success of an asynchronous operation.  Sure, if we know with 100% accuracy that the operation will complete in less than N seconds, then why not -- timers are (arguably) ok.  Nonetheless, I think it would be better to simply piggy back onto the callback function which executes when the async operation completes, and from there trigger the proper response.

I will make the necessary changes in Container.html (unit-test)

Thoughts? Comments?

**Comment by Jimgskoop** [comment]
I just tried

```
asyncTest('hide', function () {

  var deferredA = $.Deferred();

  setTimeout(function () {
    ok( ($("div.tip").size() === 0), "no tip found in DOM" );
    deferredA.resolve();
  }, 500);

  $.when(deferredA).done(function () {
    start();
  });

});    
```

And I'm getting an error that the test fails.  Not really sure why/not sure how to debug.

**Comment by Iheartweb** [comment]
I think krisk has a wAy to fix this check it in with the broken tests I'll look in the morning

**Comment by Jimgskoop** [comment]
I ended up going with the qunit standard way of using asycTest and  
setTimeout. That seems to work OK for what I need.

-Jim G

On Apr 30, 2012, at 6:43 PM, Robert Martone <reply@reply.github.com 

> wrote:
> 
> I think krisk has a wAy to fix this check it in with the broken  
> tests I'll look in the morning
> 
> Sent from my iPhone
>

**Comment by krisk** [comment]
(updated)

Hey @Jimgskoop,  `$.when` should be used when you have multiple deferred objects that need resolving when all have completed.  In your case,  you only have one, thus how you did it is fine.
