### ISSUE TITLE
Implement Carousel in Davinci

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#109]
Work with Brett to do this.

This will require the porting of lu to the page as well as a basic setup of carousel.

**Comment by Iheartweb** [comment]
This will require us to write a require shim.

**Comment by Iheartweb** [comment]
The Inject team will be looking into a solution for loading files into davinci. A require shim should still be built so that Lu has compatibility with concatenated files. @brendean I am reassigning this to you for tracking purposes. Also, the davinci peeps need some help getting a lu env up and running. We'll discuss this issue tomorrow.

Thanks.

**Comment by Jimgskoop** [comment]
Did @Jakobo ask for this to be reassigned to him during today's meeting?

**Comment by thecodedrift** [comment]
I can take it on to start working with Brett

On Friday, May 11, 2012, Jim G wrote:

> Did @Jakobo ask for this to be reassigned to him during today's meeting?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Iheartweb/Lu/issues/109#issuecomment-5657190

## 

--Jakob

**Comment by Jimgskoop** [comment]
OK.  Note that neither @Jakobo nor Brett are signed in as Lu contributers on this repo, so I can't reassign this issue.

**Comment by Iheartweb** [comment]
We'll keep it assigned to the Lu team for tracking.

**Comment by Jimgskoop** [comment]
Inject on page & console.log
Brendan & Jim enable Lu w/debug stmts.

**Comment by Iheartweb** [comment]
We'll sit down on Friday and do this.

**Comment by Iheartweb** [comment]
Missed Friday, I am goiing to take this one on on Tuesday.

**Comment by Jimgskoop** [comment]
@Iheartweb Is this issue completed?

**Comment by Iheartweb** [comment]
We are blocked by linkedin/inject#116

**Comment by Iheartweb** [comment]
To complete this in Davinci required editing all require statements in Lu, lu.js and adding an addrule for each control. If we are still blocked EOD on Friday we will proceed with a hack.
