### ISSUE TITLE
Tip Refactoring

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#118]
The tip control follows a pattern unique in Lu. @krisk @Jimgskoop, let's discuss possible changes to It's architecture.

**Comment by Jimgskoop** [comment]
@krisk @Iheartweb can you add in more detail on what to do here?  Thanks!

**Comment by Jimgskoop** [comment]
@krisk @Iheartweb -- Do you guys feel it should follow the decorator pattern?  Create an instance of Container and embellish it?  BTW, I need some background on the changes to Container, it seems really different now...

**Comment by krisk** [comment]
@Jimgskoop, yes, it should follow the decorator pattern.  We can spend time tomorrow and talk about it / design it :)
