### ISSUE TITLE
Inheritance & Decoration model

### ISSUE THREAD

**Issue by krisk** [Droppe/Lu#124]
The new inheritiance model, I think, is best explained with code.

Let's define an Animal class:

``` javascript
// Animal base class
var Animal = Class.extend(function(base) {
    return {
        // The `init` method serves as the constructor.
        init: function() {

            // Insert private functions here
            function private1(){}
            function private2(){}

            // Insert priviledged functions here
            this.privileged1 = function(){}
            this.privileged2 = function(){}
        },
        method1: function(){}
    }
});
```

`Class.extend` expects a function that returns an object literal.  That object literal is used to construct the prototype. The `init` method in the object literal acts as the constructor, which is invoked when an instance is created.  That is:

``` javascript
var animal = new Animal(); // Create a new Animal instance
```

`init` is invoked automatically.
#### Inheriting

Now, suppose I want to create a Dog class. Since a dog is essentially an animal, then it should inherit from `Animal`. Note that every class definition has access to the parent's prototype via the `base` argument (or whatever you named it, since the consumer controls this).

``` javascript
// Extend the Animal class.
var Dog = Animal.extend(function(base) {
    return {
        init: function(prop) {
            // Call the base init.
            base.init.call(this);
        },
        // Override base class `method1`
        method1: function(){},
        scare: function(){
            console.log('Dog::I scare you');
        }
    }
});
```

Create an instance of `Dog`:

``` javascript
var husky = new Dog();
husky.scare(); // "Dog::I scare you'"
```
#### Decorating

The ability to decorate instances is quite powerful.  As an example:

``` javascript
var Domesticated = function(obj, base) {
    // Override the instance' scare method
    obj.scare = function(){
        console.log('Domesticated::sorry, we dont scare');
    }

    // Add a method
    obj.kneel = function(){}

    // Bind some custom events
    $(obj).on('barking', function() {});
};
```

From the above, you can see that a decorator is merely a function that expects an instance and the base prototype, both of which are provided by the `Class` library.  Within this function, you can override, augment, bind... - that is, decorate, the instance as you please.

So, back to our `husky` example.  To decorate the instance, use `decorate`:

``` javascript
husky.decorate(Domesticated);
husky.scare(); // "Domesticated::sorry, we don't scare"
```

And there you have it.

**Comment by Jimgskoop** [comment]
So ptclass is gone, right?  What library is replacing it?

**Comment by krisk** [comment]
PTClass is gone (or will be gone entirely, soon).  The library replacing it is temporarily called "Class", since we haven't really decided on a name :p  Any ideas?

**Comment by Jimgskoop** [comment]
"Shaft".

;)

On Tue, May 15, 2012 at 4:40 PM, Kirollos Risk
reply@reply.github.com
wrote:

> PTClass is gone (or will be gone entirely, soon).  The library replacing it is temporarily called "Class", since we haven't really decided on a name :p  Any ideas?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Iheartweb/Lu/issues/124#issuecomment-5730485

## 

jimg at yojimg dot net

**Comment by Jimgskoop** [comment]
"KClass"

On Tue, May 15, 2012 at 4:51 PM, jim g jimg@yojimg.net wrote:

> "Shaft".
> 
> ;)
> 
> On Tue, May 15, 2012 at 4:40 PM, Kirollos Risk
> reply@reply.github.com
> wrote:
> 
> > PTClass is gone (or will be gone entirely, soon).  The library replacing it is temporarily called "Class", since we haven't really decided on a name :p  Any ideas?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/Iheartweb/Lu/issues/124#issuecomment-5730485
> 
> ## 
> 
> jimg at yojimg dot net

## 

jimg at yojimg dot net

**Comment by Jimgskoop** [comment]
var Animal = Class.extend(function(base) {...};

"base" is never used -- is that correct?

**Comment by Jimgskoop** [comment]
base.init.call(this) feels clunky.  Can this be wrapped up into a helper function defined within Class?

I would rather just call base(this) directly, or maybe base.init(this).

**Comment by Jimgskoop** [comment]
Finally, should this file be broken out as a separate project?

**Comment by krisk** [comment]
@Jimgskoop 

(1) "Shaft" - hahah nice.

(2) "KClass" - too ominous :p 

(3) `var Animal = Class.extend(function(base) {...};` - yes, `base` is never used in this example.  Actually, `base`, in this case, refers to the prototype of the object you're extending, which happens to be a `Class` instance (which only has `decorate` and `extend` as its methods).  That is to say, there should be really no point in ever using `base` in a top-level class.

(4) `base(this)` -  it would be nice, but impossible.   Simply using `base` as a private variable to achieve prototypal method invocation is impossible.  It would have to be a public property of the instance - `this.base`, and it would have to hold the calle, and not the prototype. To achieve this, the inheritance library would have to iterate over every function in a prototype, rebind it within a closure in which `this.base` is defined, then, any time `this.base` is invoked, it would have to release or reassign its value so another function in the prototype can use it.  Either way, that would result in the slowest inheritance model.  For example, John Resig's inheritance model works way, and it is slow.

(5) `base.init(this)` - this is achievable.  However, to do this, the inheritance library would have to create a new function for every method in the prototype - again, it makes instantiation slow.  Additionally, from a JavaScript point of view, it's confusing, as it suggests that you're passing `this` as a parameter to `init` (and therefore `init` is expecting that parameter), when in fact it's actually invoking the `init` function with a **context** of `this`.

(6) Yes, the inheritance model should be broken out as a separate project.  However, since it's really only one microscopic JavaScript file that Lu has to include anyway, we pushed it in this repo :)

**Comment by Iheartweb** [comment]
Shaft +1

@krisk we should write a client MVC Lib to end all Client MVC Libs.
1. We have a better event model.
2. We have a better class Lib
3. Catwalk is a better client side Model helper.
4. We can come up with a better router. Sammy does it much better than Backbone...
5. We can decouple View binding from the lib using our decorator. ah-hem - We can use any client side templating thingy ma-bob out there.

**Comment by Iheartweb** [comment]
I think we completely nailed this. _censored_ YEAH!!!

censored by @krisk
