### ISSUE TITLE
multiple annotations of Foo should result in one instance

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#133]
For Example: this should only create one button instance.

``` html
<a href="#three" data-lu="Button:Select Button:Load">Select and Load</a>
```

It should be decorated with both load and select.

**Comment by Jimgskoop** [comment]
Why not just "Button:Select:Load" or "Button:Load:Select"?  Or are we thinking that this is a special case of "Foo:Load Bar:Select"?

**Comment by Iheartweb** [comment]
Technically that could work too. The mappers could also be responsible for determining how the colon is treated.

**Comment by Iheartweb** [comment]
It turns out that there is an underlying issues here. Somewhere along the line the settings object is being either leaking out of scope or being cached in a closure. That means the when you have two controls on one node - the settings object will be retained and throw an error. ugghhhhhh! This might also cause some pretty hairy bugs in the future.
