### ISSUE TITLE
Accordion in Davinci

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#146]
Implement Accordion in Davinci

**Comment by Iheartweb** [comment]
Let's track bugs that effect li code in jira

**Comment by Jimgskoop** [comment]
Will anybody see 'em?  ;)

On Tue, May 29, 2012 at 5:38 PM, Robert Martone
reply@reply.github.com
wrote:

> Let's track bugs that effect li code in jira
> 
> Sent from my iPhone
> 
> On May 29, 2012, at 5:04 PM, Jim Greply@reply.github.com wrote:
> 
> > Implement Accordion in Davinci
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/linkedin/Lu/issues/146
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linkedin/Lu/issues/146#issuecomment-5999648

## 

jimg at yojimg dot net

**Comment by Iheartweb** [comment]
We are blocked by linkedin/inject#116

#116 is CLOSED

**Comment by Iheartweb** [comment]
Sean owes us some mocks

**Comment by Jimgskoop** [comment]
Working on getting this into Davinci.  Had to fix a couple of bugs in List, and am now wrangling with List unit tests.

**Comment by Jimgskoop** [comment]
List is doing some weird things inside List.select.  If you designate the LIs within a List as Containers, everything works OK.  But if you leave that off and let List auto-create Containers on each LI, List.select calls itself a second time (maybe more) and other methods chained onto List.select() won't work right, since .select becomes an asynchronous method, and the index of the List isn't updated immediately.  

I think that List needs to implement the Promise pattern so that the object returned by List.select can be chained and also execute asynchronously.  Thoughts @Iheartweb  @krisk ?

**Comment by Iheartweb** [comment]
@Jimgskoop I am still working through some issues with container setting the correct initial state.
