### ISSUE TITLE
Button should use require.ensure to load decorators

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#147]

**Comment by Iheartweb** [comment]
@krisk Assigning to you!

**Comment by Jimgskoop** [comment]
@krisk what's the status on this?

**Comment by Jimgskoop** [comment]
@krisk You said you'd have this done last Friday.  Are you blocked?

**Comment by krisk** [comment]
@Iheartweb been sidetracked.  I've changed decorators in Class to work a little differently.  I wanted to present it to you (you can check out the experimental branch in github Class).  I'm running in a few issues with inject, but I have a work around for now.  I'll push the changes once I get that resolved.
