### ISSUE TITLE
Upgrade to inject 0.3

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#155]

**Comment by Jimgskoop** [comment]
I'll take this since I've started working on it already.

**Comment by Iheartweb** [comment]
Any luck? I might skip to the .4 pre. Objections? Assign this to me if you have none.

**Comment by Jimgskoop** [comment]
Inject 0.3.0 is already in.  Note the (added) version number in
https://github.com/linkedin/Lu/blob/master/scripts/libraries/inject.js

On Wed, Jun 20, 2012 at 10:05 PM, Robert Martone
reply@reply.github.com
wrote:
