### ISSUE TITLE
Lu broken on IE7/8

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#166]
JS errors get thrown on IE7 & 8.

**Comment by Jimgskoop** [comment]
Abstract.js uses String.trim(), which isn't supported on <IE9.  See https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/String/Trim

**Comment by Iheartweb** [comment]
@Jimgskoop I am going to be working on Lu a bit over the next few days. This should be quick so I'll take it.

**Comment by Jimgskoop** [comment]
Think we fixed it.

On Fri, Jul 6, 2012 at 6:09 PM, Robert Martone
reply@reply.github.com
wrote:

> @Jimgskoop I am going to be working on Lu a bit over the next few days. This should be quick so I'll take it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linkedin/Lu/issues/166#issuecomment-6819404

## 

jimg at yojimg dot net

**Comment by Iheartweb** [comment]
Thanks!

**Comment by Jimgskoop** [comment]
String.trim() doesn't exist for IE 6/7/8 and maybe 9. I added a trim  
helper as an underscore mixin.

-Jim G

On Jul 6, 2012, at 6:47 PM, Robert Martone <reply@reply.github.com 

> wrote:
> 
> Thanks!
> 
> Sent from my iPhone
>
