### ISSUE TITLE
Viewport/Window decorator

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#176]
We need a carousel that knows how to display a viewport, e.g. multiple thumbnail images visible in a display window.  In this case, no one item is really the "selected" item.

**Comment by Iheartweb** [comment]
I'll have to see a mock of this - but I believe this is already doable with nested `<ul>`s

**Comment by Jimgskoop** [comment]
True.  I'm not a fan of the nested `<ul>` approach, though, since it's less semantic.

**Comment by Iheartweb** [comment]
@yifanz , @alvinhuynh I am impressed with you work thus far. Thanks.

**Comment by Iheartweb** [comment]
Think about dynamic loading of new items as you paginate.

**Comment by Iheartweb** [comment]
Also, consider showing partial items. < [1][2][3][4 >

**Comment by Iheartweb** [comment]
@alvinhuynh, @yifanz Please write an example for the examples folder

**Comment by alvinhuynh** [comment]
We currently have one called viewport.html located in the examples folder.  It has both examples for list and carousel.
