### ISSUE TITLE
List ready for Arbification

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#20]
-Event Cleanup
-Logic for identifying what to select should be moved to list.
-Exports Cleanup

**Comment by olivertse** [comment]
Hi,

Jim, did most of the work while I was on vacation.  I did some very minor cleanup - https://github.com/Iheartweb/AthenaUIFramework/commit/80c8e1fb91a8ee57e933bc8ae564d597ea7c5fab.

Thanks Jim!
Oliver
