### ISSUE TITLE
Tip example no longer works

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#202]
@Iheartweb, Tip no longer seems to work.  I've fixed the file bootstrapping in examples/tip.html, but of the 6 tips on the test page, only the first one seems to instantiate -- and it doesn't work either.  I'm currently debugging, just wanted to give you a heads-up.

**Comment by Jimgskoop** [comment]
in lu.js, $nodes = $element.find( this.$mapped ) $nodes is always an empty set.  I'm not using any mappers in the Tip example -- are those required?

**Comment by Iheartweb** [comment]
Tip need to be converted to Fiber/new decorator pattern. After that it
_should_ work.

**Comment by Iheartweb** [comment]
closing as a dupe of #200
