### ISSUE TITLE
Container example doesn't work

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#230]
@Iheartweb, the Container example isn't working for me.  In fact, Container.js isn't even loading.  The deferal.then within the execute function in lu.js isn't even firing:

deferral.then( function( required, module, exports ){
          var Component = require( requirement );
          component.instance = new Component( $element, settings );
          if( component.hasDependencies ){
            component.instance.one( 'dependencies-resolved', function( event, instance ){
              event.stopPropagation();
              component.deferral.resolve( component.instance );
            } );
          } else {
            component.deferral.resolve( component.instance );
          }
        } );

Any ideas?

**Comment by Iheartweb** [comment]
I added a container example: dialog.html. There were a few issues that caused some errors:
1. Firebug was throwing some error in FF 15. After upgrading, it still does - but they don't break things.
2. There was a trailing COMMA OF DEATH.
3. The 'load' button' is broken... I'll open a separate issue and assign to @jwong15 as it's important for dialog.
