### ISSUE TITLE
Mapper.js vanished?

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#266]
Just updated, nothing works because there's no mapper js file. Intentional?

**Comment by Iheartweb** [comment]
Its in the repo, are you sure?

**Comment by Jimgskoop** [comment]
My mistake, pls disregard.  I've closed that ticket.  I'm having some git issues...

-Jim G

On Oct 18, 2012, at 7:30 AM, Robert Martone wrote:

Its in the repo, are you sure?
