### ISSUE TITLE
CSS Classes During init

### ISSUE THREAD

**Issue by thecodedrift** [Droppe/Lu#32]
Since Athena uses CSS for its hooks throughout, can we add classes to the html tag as we are initializing? This would help with ensuring things render correctly when Athena does not load properly. For example, `$(html).addClass("athena-pending")` while the athena framework is loading, and `$(html).toggleClass("athena-pending athena-ready")` after the ready event fires?

The primary use case is something like a carousel. I'd like to be able to avoid the flash of unstyled content if I know JavaScript is working, but when JavaScript is disabled, let the carousel display all of its items.

**Comment by Iheartweb** [comment]
Yes!
