### ISSUE TITLE
Consolidate Container and Loader

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#38]
Container should be merged with loader. Container should additionally take a content setting. This setting should accept either a string or a URL. If it is a URL the content should be a-synced in and then an Iframe should be created with the height and width of the container and a src of the url. If the setting is a string, it should be escaped and then injected into the container.

Whenever content is injected, the container should set it's height/width to the contents height/width unless already specified w/CSS.

Also, keep in mind that the container should be as generic as possible. It's instances should respond to use case specific events and apply styles.

Yay! Root Canals are awesome.

**Comment by Jimgskoop** [comment]
"If it is a URL the content should be a-synced in and then an Iframe should be created " -- if we're AJAXing the content in from the URL, why do we need an iFrame?

**Comment by Iheartweb** [comment]
The use cases for Loader  were:

Loading content or in a tip (Mini profile)
Loading content in an accordion panel
Loading content in a tab.
Loading content in a dialog.

The above should say "If it is a URL from the same domain the content should be a-synced in otherwise, an Iframe should be created..."

I was probably hopped up on pain killer at the time of writing the above ...

In truth, we should probably give the option to force the content into an iframe even if the url originated from the same domain.

Container will be useful for other controls to extend or use. IMO because the events on other controls vary container should not inherently respond to any events. Rather, Controls like Dialog should respond to a close event ant call a close method on container. Likewise Accordion could respond to an expand event, get the content height of the containers content and then expand the container.

**Comment by Jimgskoop** [comment]
It sounds to me like Loader should inherit from Container -- is that what you're thinking?  And Tip could inherit from Loader as well.

I don't recall why we originally had Container create an internal instance of Loader, instead of going the inheritance route...?

I agree on the iframe option, too.

**Comment by Jimgskoop** [comment]
Container & Loader are mostly done.  Examples in Primer (also for Tip).  Still need to create unit tests w/Kiro's help....

**Comment by Iheartweb** [comment]
Nice!
