### ISSUE TITLE
Athena Button Causing jQuery Error

### ISSUE THREAD

**Issue by ghost** [Droppe/Lu#42]
Clicking on 'athena-data="Button"' elements on the in_arbys page, regardless of DOM placement or config/no config, causes a "event is undefined" jQuery error. All other types of buttons work fine (e.g. Button:Next, etc.).

**Comment by olivertse** [comment]
Hey Pete!

Hope all is well.  I think you mean "data-athena", but to answer your question, right now, you have to do Button:Select or Button:Next or Button:Prev, etc.  

Have a good one Pete!
Oliver

**Comment by olivertse** [comment]
Ok, I spoke with Pete and this is a bug.  Basically, when you define a button like "data-athena='Button'" and specify the "action" like "open" or any "action", you'll get an the JS error "event is undefined".

It should work like "Button:Open", etc.

**Comment by olivertse** [comment]
https://github.com/Jakobo/in_arbys/commit/bc41489203b48f38c2446af5bf1bc44d651256e2

I think this is a syntax error in the HTML.  "data-config" versus "data-athena-config".  Bye!
