### ISSUE TITLE
Use json2.js to stringify configs.

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#43]
//TODO: USING JSON.STRINGIFY WILL BREAK IN OLDER BROWSERS
  Athena.decorate = function( $element, keys, settings ) {
    var nodeKeys = ( $element.attr( ATTR ) ) ? $element.attr( ATTR ).split( ' ' ) : [];
    keys = _.union( nodeKeys, keys );
    settings = settings;
    if( settings ) {
      return $element.attr( ATTR, keys.join( ' ' ) ).attr( ATTR + '-config', JSON.stringify( settings ) );
    }
    return $element.attr( ATTR, keys.join( ' ' ) );
  };

**Comment by Iheartweb** [comment]
the above is from athena.js

**Comment by Jimgskoop** [comment]
Fixed.

https://github.com/Iheartweb/AthenaUIFramework/commit/f41d8827325ab31a729a65e582c0725b407f908b
