### ISSUE TITLE
Autoplay carousel shouldn't play when it's not visible

### ISSUE THREAD

**Issue by olivertse** [Droppe/Lu#44]
This is probably solved by application programming, but there is the case when a Carousel is in a Tab.  In that case, the Tab knows when the Carousel is and is not visible and so, the Tab can trigger a "pause" event on hide and a "play" event on show.

**Comment by Jimgskoop** [comment]
Actually the Carousel is in a Container, so maybe that should send the  
pause event when it knows it's hidden?  Good point!

-Jim G

On Dec 22, 2011, at 7:45 PM, Oliver Tse <reply@reply.github.com
