### ISSUE TITLE
MVP for Build Script

### ISSUE THREAD

**Issue by mattpowell** [Droppe/Lu#46]
MVP is:
- Asks for a path to output lu.js and Lu controls to.
- Asks what version of Lu controls to copy.
  - Subsequently, can grep for what versions are available.
- Accepts command line args
- Will combine underscore mixins, ptClass, and lu.js
  - Only if specified by user.
- Asks for a compilation level and then compiles both lu.js and Lu controls at that level.

**Comment by Iheartweb** [comment]
Looking good for an MVP.
