### ISSUE TITLE
Carousel: incorrect item transitioning

### ISSUE THREAD

**Issue by krisk** [Droppe/Lu#49]
Unit testing caught this one.

**Details**: Calling pause, then play, then pause, then play, skips items intermittently.
**Cause**: the timer
**Solution**: When the carousel is paused, the timer in the recurse() function should be cleared, otherwise the function will continue executing.

**Comment by krisk** [comment]
Just fixed this.  Looks good.

**Comment by Iheartweb** [comment]
Nice!
