### ISSUE TITLE
Build Tabs

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#56]
Build/fix Tabs control

JS Code
HTML examples
Functional completeness
Documentation + Example in Primer
Unit testing (work with Kiro)

**Comment by Iheartweb** [comment]
I believe this is more or less finished. Follow up with @krisk

**Comment by Jimgskoop** [comment]
Assigning to @krisk to see if it's truly finished.

**Comment by Iheartweb** [comment]
@Jimgskoop Let's touch base on this with @krisk  tomorrow, I suspect Tabs might need a bit of refactoring.
