### ISSUE TITLE
Dropdown Control

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#57]
Build/fix Dropdown control

JS Code
HTML examples
Functional completeness
Documentation + Example in Primer
Unit testing (work with Kiro)

**Comment by Iheartweb** [comment]
Does this include Split Button?

**Comment by Jimgskoop** [comment]
Good question -- I don't think we talked about Split Button last Friday.  Can that be rolled into this issue, or do we need a separate one?

**Comment by Iheartweb** [comment]
I'll open a sep issue for this -- just for traceability,

**Comment by Jimgskoop** [comment]
@olivertse What's the status on this -- it's due in THREE DAYS.  Thanks!

**Comment by olivertse** [comment]
Hi Jim,

I've been focusing on other things so I won't be able to meet the deadline.  For the time being, I'll be contributing very little to Lu.

Hopefully, when things settle down on some other stuff that I'm working on, I'll get back into the groove.

Oliver

**Comment by Jimgskoop** [comment]
@olivertse Please reassign this issue to a new owner if you can't get to it.

**Comment by olivertse** [comment]
Hi Jim,

I've reassigned them to Robert so that it can be reassigned.

Thanks!
Oliver

On Tue, May 15, 2012 at 10:18 AM, Jim G <
reply@reply.github.com

**Comment by jwong15** [comment]
see Robert's comment on split butons.  Essentially the same thing.  Split button = dropdown + button

https://github.com/Iheartweb/Lu/issues/72#issuecomment-5828692
