### ISSUE TITLE
Tip Control

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#58]
Build/fix Tip control

JS Code
HTML examples
Functional completeness
Documentation + Example in Primer
Unit testing (work with Kiro)

**Comment by Iheartweb** [comment]
@Jimgskoop,
You did a bunch of work on this do you want to take this over?

Pleas assign issues to me if you want me to handle any of the above - or assign the whole thing back to me.

**Comment by Iheartweb** [comment]
Tip should be refactored to use a decorator pattern. We are going to standardize a way to do this within the Lu Framework. I'll open a bug for this.

**Comment by Iheartweb** [comment]
Reopening this one as there is no resolution yet. @Jimgskoop please stash your work with tip and checkout the container unit tests before doing a Pull Request. I'll still open another bug for refactoring Tip.

**Comment by Jimgskoop** [comment]
@Iheartweb accepted my last pull request, so I'm assuming all's well here, and closing this.  Let me know otherwise!  Thanks!
