### ISSUE TITLE
Depricate Switcher, Merge functionality to container.

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#70]

**Comment by Iheartweb** [comment]
@Jimgskoop I am starting to heavily consider folding Loader into Container as well. The reason is this.

Lets say you have a carousel with 5 items. In this Carousel the first two items have static content and are stateful - SO, they should be managed by Container.

But what if the remaining items have dynamic content? - This should obviously be managed by Loader. But, does this also mean that we have two separate client-side templates for Container and Loader? They would be virtually identical.

I'd rather do something like this: 

```
{#items}
{@if cond="{idx} < 3}
 {>item content="Lorem Ipsum"}
 {else}
 {>item uri="http://www.google.com#node"}
 {/else}
{/if}
{/items}
```

Where item has a config that looks something  like:

```
{
  'Container': {
    {?url}'url': {url} {/url}
    {?content}'content': {content} {/content}
  }
}
```

We could do the same type of logic and still keep Loader and container separate but it gets nasty:

```
{
  {?url}'Loader'{url} {/url} {?content}'Container'{content} {/content}: {
    {?url}'url': {url} {/url}
    {?content}'content': {content} {/content}
}
```

What if both url and content are defined? -- You'd have to introduce more logic into the template to make sure that's not the case. - This is better done in the control.

**Comment by Jimgskoop** [comment]
That sounds OK to me. Container already knows how to source content  
from elsewhere in the DOM; Loader just adds on the XHR and iframe  
smarts.

My thinking was that any URL supercedes any local source if both are  
present, but admittedly that's not ideal.

The only caveat is that you'll probably need distinct config params  
for string, node, and URL for the source, in case you want to do  
something like inject a URL as a string to display.

-Jim G

On Apr 14, 2012, at 11:14 AM, Robert Martone <reply@reply.github.com
