### ISSUE TITLE
JsLint (all the good parts) lu.js

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#71]

**Comment by Jimgskoop** [comment]
Here's the remaining complaints from JSLint on lu.js:

lint:lu.js:28:31:Expected an identifier and instead saw 'undefined' (a reserved word).
jslint:lu.js:191:32:The Function constructor is eval.
jslint:lu.js:415:82:'JSONify' was used before it was defined.
jslint:lu.js:415:82:Missing 'new'.

Thoughts?

-Jim G

**Comment by Jimgskoop** [comment]
I am mostly concerned with 

jslint:lu.js:415:82:'JSONify' was used before it was defined.

I can't find where JSONify is defined anywhere within Lu.  Did we forget to include a library or something...?

-Jim G

**Comment by Iheartweb** [comment]
Hmmm....

this line: return $element.attr( ATTR, keys.join( ' ' ) ).attr( ATTR + '-config', JSONify( settings ) ); should be
return $element.attr( ATTR, keys.join( ' ' ) ).attr( ATTR + '-config', JSON.stringify( settings ) );

**Comment by Iheartweb** [comment]
Yeah, agree that's the only one that's problematic.

**Comment by Iheartweb** [comment]
I fixed the "JSONify" problem

**Comment by Jimgskoop** [comment]
That makes more sense!

;)

-Jim G

On Apr 7, 2012, at 3:18 AM, Robert Martone <reply@reply.github.com

**Comment by Iheartweb** [comment]
Looking good now.
