### ISSUE TITLE
Split Button

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#72]
Provide a Split button that meets DV reqs. This may not be a separate control. This may only be an IMPL of DropDown and button.

**Comment by Iheartweb** [comment]
I think this can be achieved with markup only. We may not even need dropdown. Let's talk.

**Comment by Jimgskoop** [comment]
@olivertse status?  Due in THREE DAYS.  Thanks!

**Comment by Iheartweb** [comment]
This matches the spec found @ http://msdn.microsoft.com/en-us/library/windows/desktop/aa511453.aspx
I introduced another control - Switch - It extends Abstract and is decorator by the StateDecorator - That's it.

Thoughts?

``` HTML
 <div class="split-button lu-state-closed" data-lu="Switch">
    <a href="#default-action" role="button">Action</a>
    <button data-lu="Button:State" class="arrow" data-lu-config="{
      'Button:State': {
        states: ['closed', 'open']
      }
    }">&raquo;</button>
    <ul class="menu">
      <li>
        <a href="#action1">Alt Action 1</a>
      </li>
      <li>
        <a href="#action2">Alt Action 2</a>
      </li>
      <li>
        <a href="#action2">Alt Action 3</a>
      </li>
    </ul>
  </div>
```
