### ISSUE TITLE
Improve performance of Build Script

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#78]

**Comment by Iheartweb** [comment]
UGLIFY!!!

**Comment by Jimgskoop** [comment]
@mattpowell what's the status on this issue?  It's overdue!

**Comment by Iheartweb** [comment]
@mattpowell Can you give me a rundown of the work required for this? Perhaps @krisk can take it on.

**Comment by mattpowell** [comment]
Tis done. Just need to run the compiled code through our unit tests to verify.

Side note: this is just a tweak/feature and shouldn't be holding up any development. If you're having trouble running the closure-based build, let me know and I can help you...

**Comment by Iheartweb** [comment]
Thanks @Jakobo
