### ISSUE TITLE
Explore framework performance enhancements 

### ISSUE THREAD

**Issue by Jimgskoop** [Droppe/Lu#81]
Lu needs some way to defer object instantiation -- especially in the case of having a large number of Lu controls on a single page (e.g. search results).  Robert and I brainstormed on several ways to experiment with this:
- Automatic deferred instantiation of all controls
- Flagging specific controls for deferred instantiation via some special syntax (e.g. data-lu-deferred="Button")
- Creating some sort of "deferred container" that would instantiate any controls within it in response to some external event
- Lots of similar objects -- centralized configs?

**Comment by Iheartweb** [comment]
@krisk, @mattpowell - I know you guys have lots of perf ideas. Get them down here....

**Comment by Iheartweb** [comment]
I think the Button/Tip and Inheritance makes will do the perf trick. We will readdress other ideas after Davinci.
