### ISSUE TITLE
Revisit Unit Tests for Container

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#82]
Switcher and Loader were merged into Container. The Unit tests need to be updated.

**Comment by Iheartweb** [comment]
@krisk I ran into a problem when writing unit tests for Container.

```
  test( 'update', function() {
     var success = false;

     expect( 1 );

     Container.on( 'updated', function( event ){
       success = ( Container.getContent() === 'Fi ' );
       //LOOK INTO PROBLEM UNBINDING EVENTS
       //Container.off( 'updated' );
     } );

     Container.trigger( 'update', 'Fi ' );

     ok( success, 'content was updated successfully' );
  } );
```

When I comment the Container.off line it throws an Error. Likewise, if I use .one the same error is thrown. Is there a problem with our binding and unbinding in Abstract.js?

**Comment by krisk** [comment]
I will take a look.
