### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#85]
Primer
Unit Testing
Should Use Container
Cleanup

**Comment by Iheartweb** [comment]
This should prob just be a container. Let's chat before too much work is done

**Comment by Iheartweb** [comment]
This is dependent on the new State Button. I'll talk about it on Fri.

**Comment by Jimgskoop** [comment]
Assigning this to one of the new guys @brendean

**Comment by Iheartweb** [comment]
This should be achievable only through markup using container and buttons. Some basic styling will be needed too. assigning to mr. @jwong15 as @brendean is taking on some other stuff.

**Comment by Jimgskoop** [comment]
Status?  This is due in THREE DAYS.

**Comment by Jimgskoop** [comment]
See https://gist.github.com/c26cd90612d90dc9c654

**Comment by jwong15** [comment]
Was able to prove dialogs can be created through markup, containers and buttons.  See gist. 

No push required.
