### ISSUE TITLE
Code Sweep

### ISSUE THREAD

**Issue by Iheartweb** [Droppe/Lu#87]

**Comment by Iheartweb** [comment]
@Jimgskoop,

Do you think we should rename button? I think that it is a misleading name when you start using it on checkboxes and radios.

Thoughts?

**Comment by Jimgskoop** [comment]
Nope.

-Jim G

On May 21, 2012, at 12:00 PM, Robert Martone <reply@reply.github.com

**Comment by Jimgskoop** [comment]
EventMorpher decorator. Button can use it, so can form elements.

-Jim G

On May 21, 2012, at 12:00 PM, Robert Martone <reply@reply.github.com

**Comment by Iheartweb** [comment]
Good Idea!

Button stays Button.

I am also thinking about our dir structure. Would this be better:

lu/
--controls/
--decorators
--lu.js
--config.js
--underscore-mixins.js

if you think so - we'll present it to the group on Friday - and make the change before we move to the LI repo.

Thanks!

**Comment by Jimgskoop** [comment]
I'm ok with the current dir structure.

-Jim G

On May 21, 2012, at 2:18 PM, Robert Martone <reply@reply.github.com
